Universal implementation for sending "done"/"quit" signals to GCP upon completion (with host number added per request), depending on the return value of the SMuRF operation. Also, removed second GCP signaling from smurf_autotune, which I mistakenly added yesterday...

diff --git a/smurf_autotune b/smurf_autotune
--- a/smurf_autotune
+++ b/smurf_autotune
@@ -10,13 +10,13 @@
 #
 # Updated 20190206 AK: Simpler file timestamping without awk
 
+SCRIPTS="$HOME/smurf/scripts"
+
 echo "Auto-tune SMURF..."
 $HOME/smurf_cmd --tune 
-# catch error signals?
 
-# send a signal saying we're done, GCP can move on from here
-$GCP_DIR/../scripts/keck/controlSystem command 'signal/send done34'
-
+# Send completion signal to GCP with host num (exits on error)
+source $SCRIPTS/gcp_signal $? 1
 
 echo "Getting tuning parameters and dumping to file"
 
@@ -26,6 +26,5 @@ filepath=/data/keckdaq/tuning/$filename
 
 $HOME/smurf_cmd --status > $filepath
 
-# send signal that we're done?
-$GCP_DIR/../scripts/keck/controlSystem command 'signal/send done'
+
 
diff --git a/smurf_bias_bump b/smurf_bias_bump
--- a/smurf_bias_bump
+++ b/smurf_bias_bump
@@ -12,10 +12,12 @@
 # Author: Attila Kovacs
 # Version: 23 October 2018
 
+
 BIAS_INCREMENT=20
 DWELL=5
 INTERVAL=3
 
+SCRIPTS="$HOME/smurf/scripts"
 
 if [ "$#" -ge "1" ] ; then
   BIAS_INCREMENT=$1
@@ -32,3 +34,7 @@ fi
 echo "SMURF bias bumping..."
 
 $HOME/smurf_cmd --tes-bump --tes-bump-wait $DWELL
+
+# Send completion signal to GCP (exits on error)...
+source $SCRIPTS/gcp_signal $?
+
diff --git a/smurf_full_loadcurve b/smurf_full_loadcurve
--- a/smurf_full_loadcurve
+++ b/smurf_full_loadcurve
@@ -16,7 +16,8 @@
 # Version: 23 October 2018
 # Edited 20181121 by CY at Pole to match MCE version in arguments
 
-BIAS_CONVERT="$HOME/smurf/scripts/smurf_bias_convert"
+SCRIPTS="$HOME/smurf/scripts"
+BIAS_CONVERT="$SCRIPTS/smurf_bias_convert"
 
 STREAM_ON="0"
 BIAS_START=`$BIAS_CONVERT 10000` 
@@ -41,12 +42,13 @@ if [ "$#" -ge "4" ] ; then
 fi
 
 if [ "$STREAM_ON" -gt "0" ] ; then
- $HOME/smurf/scripts/smurf_make_runfile # this script auto dumps to pipe
- $HOME/smurf/scripts/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run 
+ $SCRIPTS/smurf_make_runfile # this script auto dumps to pipe
+ $SCRIPTS/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run 
 fi
 
 echo "Generate a full IV curve SMURF..."
 $HOME/smurf_cmd --slow-iv --iv-bias-high $BIAS_START --iv-bias-low 0 --iv-bias-step $BIAS_STEP --iv-wait-time $BIAS_DWELL
 
-# signal that we are done
-$GCP_DIR/../scripts/keck/controlSystem command "signal/send done"
+# Send completion signal to GCP (exits on error)...
+source $SCRIPTS/gcp_signal $?
+
diff --git a/smurf_make_plc_script b/smurf_make_plc_script
--- a/smurf_make_plc_script
+++ b/smurf_make_plc_script
@@ -13,7 +13,8 @@
 # Author: Attila Kovacs
 # Version: 23 October 2018
 
-BIAS_CONVERT="$HOME/smurf/scripts/smurf_bias_convert"
+SCRIPTS="$HOME/smurf/scripts"
+BIAS_CONVERT="$SCRIPTS/smurf_bias_convert"
 
 STREAM_ON="0"
 BIAS_START=`$BIAS_CONVERT 5000`
@@ -39,7 +40,7 @@ if [ "$#" -ge "4" ] ; then
 fi
 
 
-PLC_FILE=$HOME/smurf/scripts/state/plc.parms
+PLC_FILE=$SCRIPTS/state/plc.parms
 
 if [ -f $PLC_FILE ] ; then
   rm -f $PLC_FILE
@@ -55,12 +56,10 @@ echo "BIAS_START=$BIAS_START" >> $PLC_FILE
 echo "BIAS_STEP=$BIAS_STEP" >> $PLC_FILE
 echo "BIAS_DWELL=$BIAS_DWELL" >> $PLC_FILE
 
-RESULT=$?
+result=$?
 
 echo "Created temporary partial load-curve parameter file."
 
-#return $RESULT
-echo $RESULT
+# Send completion signal to GCP (exits on error)...
+source $SCRIPTS/gcp_signal $result
 
-# signal done
-$GCP_DIR/../scripts/keck/controlSystem command "signal/send done"
diff --git a/smurf_partial_loadcurve b/smurf_partial_loadcurve
--- a/smurf_partial_loadcurve
+++ b/smurf_partial_loadcurve
@@ -12,7 +12,8 @@
 # Author: Attila Kovacs
 # Version: 23 October 2018
 
-BIAS_CONVERT="$HOME/smurf/scripts/smurf_bias_convert"
+SCRIPTS="$HOME/smurf/scripts"
+BIAS_CONVERT="$SCRIPTS/smurf_bias_convert"
 
 STREAM_ON="0"
 BIAS_START=`$BIAS_CONVERT 10000`
@@ -38,13 +39,14 @@ if [ "$#" -ge "4" ] ; then
 fi
 
 if [ "$STREAM_ON" -gt "0" ] ; then
- $HOME/smurf/scripts/smurf_make_runfile
- $HOME/smurf/scripts/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run
+ $SCRIPTS/smurf_make_runfile
+ $SCRIPTS/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run
 fi
 
 echo "Generate a partial IV curve SMURF..."
 $HOME/smurf_cmd --slow-iv --iv-bias-high $BIAS_START --iv-bias-low 0 --iv-bias-step $BIAS_STEP --iv-wait-time $BIAS_DWELL
 
-# send signal that we're done?
-$GCP_DIR/../scripts/keck/controlSystem command 'signal/send done'
+# Send completion signal to GCP (exits on error)...
+source $SCRIPTS/gcp_signal $?
+
 
diff --git a/smurf_run_plc_script b/smurf_run_plc_script
--- a/smurf_run_plc_script
+++ b/smurf_run_plc_script
@@ -5,18 +5,18 @@
 # Author: Attila Kovacs
 # Version: 23 October 2018
 
-PLC_FILE=$HOME/smurf/scripts/state/plc.parms
+SCRIPTS="$HOME/smurf/scripts"
+PLC_FILE=$SCRIPTS/state/plc.parms
 
 source $PLC_FILE
 
 if [ "$STREAM_ON" -gt "0" ] ; then
- $HOME/smurf/scripts/smurf_make_runfile
- $HOME/smurf/scripts/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run
+ $SCRIPTS/smurf_make_runfile
+ $SCRIPTS/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run
 fi
 
 echo "Generate a partial IV curve SMURF..."
-#HOME/smurf_cmd --slow-iv --iv-bias-high-current $BIAS_START --iv-bias-low-current 0 --iv-bias-step-current $BIAS_STEP --iv-wait-time $BIAS_DWELL
 $HOME/smurf_cmd --plc --iv-bias-high $BIAS_START --iv-bias-step $BIAS_STEP --iv-wait-time $BIAS_DWELL
 
-# send signal that we are done
-$GCP_DIR/../scripts/keck/controlSystem command "signal/send done"
+# Send completion signal to GCP (exits on error)...
+source $SCRIPTS/gcp_signal $?
